version: "3"
services:
  db:
    image: mysql
    container_name: todo_db
    ports:
      - 33065:3306
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: ./docker/api/php.dockerfile
    container_name: todo_api
    volumes:
      - ./src/api:/var/www/html
    depends_on:
      - db

  webserver:
    build:
      context: .
      dockerfile: ./docker/webserver/webserver.dockerfile
    container_name: todo_webserver
    ports:
      - 8006:80
    volumes:
      - ./src/api:/var/www/html
      - ./docker/webserver/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/frontend.dockerfile
    container_name: todo_frontend
    ports:
      - 3000:80

  # cron:
  #   build:
  #     context: .
  #     dockerfile: ./docker/cron.dockerfile
  #   container_name: todo_cron
  #   volumes:
  #     - ./src/api:/var/www/html
  #   depends_on:
  #     - database
