version: "3"
services:
  db:
    image: mysql
    container_name: todo_db
    ports:
      - 33065:3306
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/backend-api/data:/var/lib/mysql

  app:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    container_name: todo_app
    volumes:
      - ./src/backend-api:/var/www/html
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: todo_webserver
    ports:
      - 8006:80
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # cron:
  #   build:
  #     context: .
  #     dockerfile: ./docker/cron.dockerfile
  #   container_name: todo_cron
  #   volumes:
  #     - ./src/backend-api:/var/www/html
  #   depends_on:
  #     - database
