version: "3"
services:
  db:
    image: mysql
    container_name: todo_db
    ports:
      - 33065:3306
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql

  api:
    container_name: todo_api
    image: jplansdocker/laravel-nuxt-webtodo-api
    depends_on:
      - db

  webserver:
    image: laravel-nuxt-webtodo-server
    container_name: todo_webserver
    ports:
      - 8006:80
    depends_on:
      - api
  
  frontend:
    image: jplansdocker/laravel-nuxt-webtodo-app
    container_name: todo_frontend
    ports:
      - 3000:80